---
title: "Creative 3: Areas and Locations"
author: "Meghan Casey"
date: September 30, 2020
output: 
  html_document:
    theme: "cosmo"
    toc: true
    toc_depth: 3  
    toc_float: true    
    highlight: "tango"
---
### Load Libraries
```{r, message = FALSE}
library(sf)
library(tidyverse)
library(ggthemes)
library(ggspatial)
library(units)
library(nngeo)
```

### Load Data
##### I'm using data from Analyze Boston.
```{r}
wards <- st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/398ee443f4ac49e9a0b7facf80afc20f_8.kml?outSR={%22latestWkid%22:2249,%22wkid%22:102686}", quiet = TRUE)

lib <- st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/cb00f9248aa6404ab741071ca3806c0e_6.kml?outSR={%22latestWkid%22:2249,%22wkid%22:102686}", quiet = TRUE)

planning <- st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/a6488cfd737b4955bf55b0342c74575b_0.kml?outSR={%22latestWkid%22:2249,%22wkid%22:102686}", quiet = TRUE)

school <- st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/cbf14bb032ef4bd38e20429f71acb61a_2.kml?outSR={%22latestWkid%22:2249,%22wkid%22:102686}", quiet = TRUE)
```

### Transforming Data
##### I'll be using the Massachusetts State Plane system
```{r}
MA_state_plane <- "+proj=lcc +lat_1=42.68333333333333 +lat_2=41.71666666666667 +lat_0=41 +lon_0=-71.5 +x_0=200000.0001016002 +y_0=750000 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs"

wards <- wards %>%
  st_transform(MA_state_plane)

lib <- lib %>%
  st_transform(MA_state_plane)

planning <- planning %>%
  st_transform(MA_state_plane)

school <- school %>%
  st_transform(MA_state_plane)
```

```{r}
ggplot(wards) +
  geom_sf(fill = "gray95", color = "gray40", size = 0.25) +
  geom_sf(data = lib, color = "aquamarine4", size = 1.5) +
  geom_sf(data = school, color = "orangered3", size = 1.5, alpha = 0.5) +
  geom_sf(data = planning, fill = NA, color = "goldenrod4", size = .60) +
  
  theme_pander()+
  annotation_scale()
```
### Creating a Buffer
##### How many schools are withing one mile of a library?
```{r}
lib_buffer <- st_buffer(lib, dist = 1610) %>%
  st_union()

ggplot(lib_buffer) +
  geom_sf(fill = "aquamarine4", alpha = 0.25)+
  geom_sf(data = wards, fill = NA, alpha = 0.5) +
  theme_map()
```

```{r}
lib_school <- school[lib_buffer,]

ggplot(lib_buffer)+
  geom_sf(fill = "aquamarine4", alpha = 0.25)+
  geom_sf(data = wards, fill = NA, alpha = 0.5) +
  geom_sf(data = lib_school,
          color = "orangered3",
          size = 1.5)+
  theme_map()
```

```{r}
school <- school %>%
  st_join(lib_school) %>%
  mutate(by_lib = !is.na(Name.y))
```

```{r}
n_lib_school <- sum(school$by_lib)
n_lib_school
```

```{r}
n_school <- length(school$by_lib)

pct_lib_school <- n_lib_school / n_school

pct_lib_school
```

##### So just under a quarter of Boston Colleges and Universities are within a mile of a public library.
```{r}
left_side  <- st_bbox(school)$xmin
top_side <- st_bbox(school)$ymax

ggplot(wards) +
  geom_sf(fill = "white", color = "gray40", size = 0.25) +
  geom_sf(data = school, size = 1,
          aes(color = by_lib)) +
  scale_color_manual(values = c("aquamarine4", "orangered3"),
          name = "Boston Collages\nby Distance to\nPublic Library", 
          labels = c("No school withing 1 mile",
                     "School within 1 mile")) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "bl",
                         style = north_arrow_fancy_orienteering()) +
  annotate(geom = "text", x = left_side, 
           y = top_side, 
           label = paste("Of the ", 
                         prettyNum(n_school, big.mark = ","),
                         " Colleges in Boston\n", 
                         prettyNum(n_lib_school, big.mark = ","),
                         " (", 
                         prettyNum(100*pct_lib_school, digits = 0),
                         "%) are within 1\nmile of a public library.",
                         sep = ""),
           hjust = 0, vjust = 0, size = 3) +
  theme_map() +
  theme(panel.background = element_rect(fill = alpha("cadetblue4", 0.15)),
        legend.position = "left")
```

### Counting Points in a Polygon
```{r}
wards <- wards %>%
  mutate(n_school = lengths(st_covers(wards, school)))


ggplot(wards) +
  geom_sf(color = NA,
          aes(fill = n_school))+
  scale_fill_viridis_c(name = "Boston Wards\nby Number\nof Colleges",
                      breaks = breaks <- seq(0, 20, by = 5)) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tl",
                       style = north_arrow_fancy_orienteering()) +
  
  theme_map() +
  theme(legend.position = "left")

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```