---
title: "Creative 4: Lines and Networks"
author: "Meghan Casey"
date: October 7, 2020
output: 
  html_document:
    theme: "cosmo"
    toc: true
    toc_depth: 3  
    toc_float: true    
    highlight: "tango"
---
### Load Libraries
```{r, message = FALSE}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
library(data.table)
library(png)
library(grid)
library(ggimage)
```

### Load Data
```{r}
WGS <- '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'
```

```{r}
dogs <- read.csv("Dogs_of_Cambridge.csv")
```

```{r}
dogs1 <- st_as_sf(dogs, coords = c("long", "lat"), crs = WGS)
```

### Get Street Data
```{r}

cambridge_street_query <- opq(bbox = 'Cambridge MA USA') %>%
  add_osm_feature(key = 'highway')

cambridge_street_query %>%
  osmdata_xml(file = 'OTP/graphs/default/cambridge_streets.osm')

cambridge_street_features <- cambridge_street_query %>%
  osmdata_sf()

cambridge_streets <- cambridge_street_features$osm_lines %>%
  st_transform(crs = WGS)
```

### Plot Data
``` {r}
ggplot(cambridge_streets) +
  geom_sf()+
  theme_map()
```

### OTP Java Trip Planner Download
```{r}
path_otp <- otp_dl_jar("OTP")
```
### Build a Graph
```{r, message = FALSE, results = 'hide'}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar", sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024)
```
### Launch OTP
```{r}
otp_setup(otp = path_otp, dir = path_data, memory = 1024)

# Connect to opentripplanner
otpcon <- otp_connect()
```

### Create Isochrone for 5 min walk
```{r}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = dogs1, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = WGS) %>%
  mutate(mode = "walk")
```
```{r}
iso_5min_bike <- 
  otp_isochrone(otpcon = otpcon, fromPlace = dogs1, 
                mode = "BICYCLE", cutoffSec = 300) %>%
  st_transform(crs = WGS) %>%
  mutate(mode = "bike")
```

```{r}
iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = dogs1, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = WGS) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_5min_drive, iso_5min_bike, iso_5min_walk)
```
```{r}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin

ggplot(iso_all_modes) +
  annotation_map_tile(type = "cartolight", zoomin = 0, progress = "none") +
  geom_sf(aes(fill = mode), color = "NA", alpha = 0.5) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_manual(values = c("gold1", "orange2", "tomato4"),
                     name = "Corgis that are reachable\nwithin 5 minutes",
                       labels = c("By car", "By Bike", "By foot")) +
  theme_map() +
  theme(legend.background = element_blank(), legend.position = "left") +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")

```
```{r}
otp_stop()
```

```{r}

iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(bike))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance of a corgi\n(square km)",
            breaks = breaks <- seq(10000, 130000, by = 20000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute biking distance of a corgi\n(square km)",
            breaks = breaks <- seq(0, 700000, by = 100000),
            labels = breaks / 1000000) +
  theme_bw()
```
### Buffer
```{r}
address <- st_read("168 Western Avenue, Cambridge, MA.kml")
```
```{r}
    
ggplot(iso_5min_bike) +
  annotation_map_tile(type = "cartolight", zoomin = 0, progress = "none") +
  geom_sf(aes(fill = mode), color = "NA", alpha = 0.5) +
  geom_sf(data = address, color = "black", size = 5, pch = 4,) +
  geom_sf(data = dogs1, size = 2, color = "gray30") +
  scale_fill_manual(values = c("salmon1"),
                     name = "Corgis that are reachable\nwithin 5 minutes",
                       labels = c("By bike")) +

  theme_map() +
  theme(legend.background = element_blank(), legend.position = "left") +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")

```

