---
title: "Creative 2: Projections + Distortions"
author: "Meghan Casey"
date: September 24, 2020
output: 
  html_document:
    theme: "cosmo"
    toc: true
    toc_depth: 3  
    toc_float: true
    highlight: "tango"
---
### Load Libraries
``` {r load libraries, message = FALSE}
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(ggplot2)
library(ggspatial)
library(ggthemes)
library(tidyverse)
library(wesanderson)
library(RColorBrewer)
library(cartogram)
```

### Get Data
```{r}
states_info <- ne_states(country = "France")

```

### Plain Maps
#### World Map
``` {r}
world <- ne_countries(scale = 50, returnclass = "sf") 

world_map <- ggplot(world) + 
  geom_sf() +
  theme_pander()

world_map
```

#### Countries in South America
``` {r}
sa_countries <- world %>%
  filter(continent == "South America")

sa_map <- ggplot(sa_countries)+
  geom_sf() +
  theme_pander()

sa_map
```

#### Provinces in France
``` {r}
france_provinces <- ne_states(country = "France", 
                              returnclass = "sf") %>%
  filter(name != "Guyane française",
         name != "Martinique",
         name != "Guadeloupe",
         name != "La Réunion",
         name != "Mayotte")

france_map <- ggplot(france_provinces) +
  geom_sf()+
  theme_pander()

france_map
```

#### US States
``` {r}
us_states <- ne_states(country = "United States of America",
                       returnclass = "sf") %>%
  filter(name != "Alaska",
         name != "Hawaii")

us_map <- ggplot(us_states) +
  geom_sf() +
  theme_pander()

us_map
```

### Reprojecting Maps
#### South America Map
```{r}
sa_map + annotation_scale()
```
#### US Map
```{r}
#US
USA_AEA <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=clrk66 +units=m +no_defs"
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"
WA_state_plane <- "+proj=lcc +lat_1=47.5 +lat_2=48.73333333333333 +lat_0=47 +lon_0=-120.8333333333333 +x_0=500000 +y_0=0 +ellps=GRS80 +units=m +no_defs"
WI_state_plane <- "+proj=lcc +lat_1=46.76666666666667 +lat_2=45.56666666666667 +lat_0=45.16666666666666 +lon_0=-90 +x_0=600000 +y_0=0 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs"
```

```{r}
ggplot(us_states) +
  geom_sf() +
  coord_sf(crs = USA_AEA) +
  theme_pander()
```
```{r}
ggplot(us_states) +
  geom_sf() +
  coord_sf(crs = MA_state_plane) +
  theme_pander()
```
```{r}
ggplot(us_states) +
  geom_sf() +
  coord_sf(crs = WA_state_plane) +
  theme_pander()
```

```{r}
ggplot(us_states) +
  geom_sf() +
  coord_sf(crs = WI_state_plane) +
  theme_pander()
```

#### US Transformed
```{r}
states_transformed <- us_states %>%
  st_transform(crs = USA_AEA)

ggplot(states_transformed) +
  geom_sf() +
  theme_pander()
```

```{r}
states_transformed_wi <- us_states %>%
  st_transform(crs = WI_state_plane)

ggplot(states_transformed_wi) +
  geom_sf() +
  theme_pander()
```

```{r}
states_transformed_ma <- us_states %>%
  st_transform(crs = MA_state_plane)

ggplot(states_transformed_ma) +
  geom_sf() +
  theme_pander()
```
### Chloropleth Map
```{r message =FALSE}
usa_data <- read_csv("covid_data.csv")

covid_states <- states_transformed %>%
  left_join(usa_data, by = c("name" = "Province_State")) %>%
  mutate(pop = 100000 * Confirmed / Incident_Rate) %>%
  select(name, pop, Confirmed, Deaths, Recovered, Active)
```

``` {r}
ggplot(covid_states, aes(fill = Confirmed)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(
    name = "Number of\nconfirmed\nCOVID-19\ncases\nas of\nSeptember\n17, 2020",
    breaks = seq(100000, 700000, by = 100000),
    labels = formatC(seq(100000, 700000, by = 100000),
                     big.mark = ",", format = "f", digits = 0)) +
  theme_map() +
  theme(legend.background = element_blank())

```
### Continuous Cartogram
```{r message= FALSE}
covid_carto_cont <- covid_states %>%
  cartogram_cont("pop")

ggplot(covid_carto_cont, aes(fill = Confirmed)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(
    name = "Number of\nconfirmed\nCOVID-19\ncases\nas of\nSeptember\n17, 2020",
    breaks = seq(100000, 700000, by = 100000),
    labels = formatC(seq(100000, 700000, by = 100000),
                    big.mark = ",", format = "f", digits = 0)) +
theme_map() +
  theme(legend.background = element_blank())
```

### Non-Continuous Cartogram
```{r}
covid_carto_ncont <- covid_states %>%
  cartogram_ncont("pop")

ggplot(covid_carto_ncont, aes(fill = Confirmed)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(
    name = "Number of\nconfirmed\nCOVID-19\ncases\nas of\nSeptember\n17, 2020",
    breaks = seq(100000, 700000, by = 100000),
    labels = formatC(seq(100000, 700000, by = 100000),
                    big.mark = ",", format = "f", digits = 0)) +
theme_map() +
  theme(legend.background = element_blank()) 
```

### Dorling Cartogram
```{r}
covid_carto_dorling <- covid_states %>%
  cartogram_dorling("pop")

ggplot(covid_carto_dorling, aes(fill = Confirmed)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(
    name = "Number of\nconfirmed\nCOVID-19\ncases\nas of\nSeptember\n17, 2020",
    breaks = seq(100000, 700000, by = 100000),
    labels = formatC(seq(100000, 700000, by = 100000),
                    big.mark = ",", format = "f", digits = 0)) +
theme_map() +
  theme(legend.background = element_blank())
```
### Proportional Symbol Map
```{r}
covid_centroids <- covid_states %>%
  st_centroid()

ggplot(states_transformed_wi) +
  geom_sf(color = "dimgray", fill = NA) +
  geom_sf(data = covid_centroids,
          aes(size = Confirmed),
          alpha = 0.65, color = "tomato3") +
  scale_size_continuous(
    name = "Number of\nconfirmed\nCOVID-19\ncases\nas of Sept.\n17, 2020",
    breaks = seq(100000, 700000, by = 100000),
    labels = formatC(seq(100000, 700000, by = 100000),
                    big.mark = ",", format = "f", digits = 0),
    range = c(0,15)) +
theme_pander()
```